[package]
name = "dawn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"
futures = "0.3.21"

[build-dependencies]
bindgen = "0.59"
cc = "1.0"
serde_json = "1.0.79"
