[package]
name = "wgslsmith_harness"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.5"
log = "0.4"
env_logger = "0.9"
pollster = "0.2"
wgpu = "0.11"
